### PR TITLE
[make:entity] fix compatibility with api-platform 3.0

### LINKED ISSUE #1198: MakeEntity is not compatible with api-platform 3.0
Api-platform 3.0 use ApiPlatform\Metadata\ApiResource class instead ApiPlatform\Core\Annotation\ApiResource, but MakerEntity still use it.

### PR DESCRIPTION
**Pull request by yobrx**
I fixed #1198, but I don't know how launch tests suites easily, I don't have found documentation for that.

### CODE REVIEW

**Comment by weaverryan** [comment]
We need to push a fix for the test suite - a recipe change upstream broke things. 

But, to run tests locally, you can run `composer install` then `./vendor/bin/simple-phpunit`. You will likely also need to tweak the `TEST_DATABASE_DSN` setting in `phpunit.xml.dist` to match your local settings. The test suite is HUGE and slow - so I usually target the specific tests that I want to run :)

**Comment by yobrx** [comment]
Thanks ! I have failures but not (normally) related to my dev.

**Comment by jrushlow** [comment]
@yobrx - I've just merged in a few fixes to our CI. Doing a rebase against `main` should fix some of the CI failures we're seeing here

**Comment by yobrx** [comment]
It's green, except one test on [6.2.x](https://github.com/symfony/maker-bundle/actions/runs/3092586683/jobs/5004024578)

**Review by weaverryan — APPROVED** [review]
The 6.2 failure looks weird and probably a real failure - but certainly unrelated to this PR 👍

File: src/Maker/MakeEntity.php [hunk 1]
```diff
@@ -317,10 +318,17 @@ public function generate(InputInterface $input, ConsoleStyle $io, Generator $gen
     public function configureDependencies(DependencyBuilder $dependencies, InputInterface $input = null): void
     {
         if (null !== $input && $input->getOption('api-resource')) {
-            $dependencies->addClassDependency(
-                ApiResource::class,
-                'api'
-            );
+            if (class_exists(LegacyApiResource::class)) {
```
Comment (dunglas) [inline src/Maker/MakeEntity.php:321]: I would test for `ApiResource` first because in 2.7 both classes exist, and we prefer using the non-deprecated attribute.

**Review by dunglas — CHANGES_REQUESTED** [review]

File: src/Maker/MakeEntity.php (hunk 1 above)
Comment (yobrx) [reply src/Maker/MakeEntity.php]: Hi Kévin, I fixed that.

**Review by dunglas — APPROVED** [review]
Thank you Yoann!!

**Review by jrushlow — APPROVED** [review]
Awesome! Thank you @yobrx
