### PR TITLE
make:crud | Improvements

### LINKED ISSUE #234: make:crud does not handle DateInterval objects
The generated index and show pages of an entity with a `DateInterval` will crash, due to `DateInterval` not being able to be cast to string.

DateTimeInterfaces generate something like this:
`{{ obj.endDate ? obj.endDate|date('Y-m-d') : '' }}`

Intervals generate something like this:
`<td>{{ obj.period }}</td>`

The following should do the trick, at least as a default.
`<td>{{ obj.period.format('%Y-%m-%d') }}</td>`

### LINKED ISSUE #270: make:crud XType (or XController)
I tried to execute this command except that it did not work as expected ...
make:crud XType
When command make:crud ends with "Type", the form isn't created correctly. (XType.php instead of XTypeType.php).
Bug may be reproduced with "Controller" instead of "Type".

### PR DESCRIPTION
**Pull request by sadikoff**
Added datetimetz, *_immutable, dateinterval and json fileds processing.

closes #234
closes #270

### CODE REVIEW

File: src/GeneratorTwigHelper.php [hunk 1]
```diff
@@ -31,15 +31,29 @@ public function getEntityFieldPrintCode($entity, $field): string
...
                 $printCode .= ' ? '.$printCode.'|date(\'Y-m-d\') : \'\'';
                 break;
+            case 'time_immutable':
             case 'time':
                 $printCode .= ' ? '.$printCode.'|date(\'H:i:s\') : \'\'';
                 break;
+            case 'json':
+            case 'json_array':
+                $printCode .= ' is iterable ? '.$printCode.'|join(\', \') : '.$printCode;
+                break;
```
Comment (weaverryan) [inline src/GeneratorTwigHelper.php]: Interesting! From looking at the docs, it seems like the value in this field will always be an `array` or `null`. Which case were you covering with the `is iterable`?

And, because the array can be an associative array, the `|join` won't look quite right in those cases. We could use `dump()` WDYT?

**Comment by weaverryan** [comment]
> How about adding new test cases to make sure these behave as intended?
It should be easy enough to add them right here:

I agree! And actually, this test could be even a little bit cooler if we actually "rendered" the result through Twig (passing in some real `entity` object) and asserted the final *output* (instead of or in addition to asserting the Twig code that should be printed). But... that's not a requirement :).

File: src/GeneratorTwigHelper.php (hunk 1 above)
Comment (sadikoff) [reply src/GeneratorTwigHelper.php]: I'll check it again. I thought there could be string value.

`dump()` is a good idea, but will it work without debug package?

Comment (weaverryan) [reply src/GeneratorTwigHelper.php]: It believe that it DOES work without `debug` - it reverts to `var_dump()`. We can add a `json` field to our entity in the functional test to be sure.

Comment (weaverryan) [reply src/GeneratorTwigHelper.php]: Oh, you know what? Let's use `|json_encode`. That will print nicely, and make it very obvious that this is a JSON field. And, it will definitely work :).

@sadikoff if you agree, can you make that change? Also, if you rebase from the latest master, the tests should be closer to passing.

**Comment by sadikoff** [comment]
[c769605](https://github.com/symfony/maker-bundle/pull/241/commits/c769605d55d7dafb1b174e828da16848fd357069) will close #277

**Comment by weaverryan** [comment]
@sadikoff Can you rebase this? I want to make sure the tests pass with the latest changes on master. Also, there are 2 changes in this PR to `.travis.yml` - do we want those?

**Comment by sadikoff** [comment]
@weaverryan ok, I'll rebase it

P.S. I think travis will be more stable with this changes

**Comment by weaverryan** [comment]
Thanks Vladimir!
