### PR TITLE
[MakeDocker] add support for .yml docker-compose files

### LINKED ISSUE #777: [Docker][database] the maker does not work because of the YamlSourceManipulator
I used https://github.com/dunglas/symfony-docker but I edit the files to use .yaml instead of .yml ([see the PR](https://github.com/dunglas/symfony-docker/pull/103)).

But I get an error when running the maker: 

```
>…m/lyrixx/SFLive-Paris2016-Workflow(docker +) bin/console make:docker:data -v

- Docker Compose Setup-
-----------------------

 We found your existing docker-compose.yaml: Let's update it!

 Which database service will you be creating?:
  [0] MySQL
  [1] MariaDB
  [2] Postgres
 > 2

 For a list of supported versions, check out https://hub.docker.com/_/postgres

 What version would you like to use? [alpine]:
 > 



In YamlSourceManipulator.php line 868:
                                                                     
  [Symfony\Bundle\MakerBundle\Util\YamlManipulationFailedException]  
  Cannot find the original value "80:80"                             
                                                                     

Exception trace:
  at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:868
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->findEndPositionOfValue() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:568
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->advanceBeyondValue() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:215
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:207
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:207
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:207
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->updateData() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/YamlSourceManipulator.php:88
 Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator->setData() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Util/ComposeFileManipulator.php:72
 Symfony\Bundle\MakerBundle\Util\ComposeFileManipulator->addDockerService() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Maker/MakeDockerDatabase.php:131
 Symfony\Bundle\MakerBundle\Maker\MakeDockerDatabase->generate() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/vendor/symfony/maker-bundle/src/Command/MakerCommand.php:104
 Symfony\Bundle\MakerBundle\Command\MakerCommand->execute() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/gregoire/dev/github.com/lyrixx/symfony/src/Symfony/Component/Console/Application.php:142
 Symfony\Component\Console\Application->run() at /home/gregoire/dev/github.com/lyrixx/SFLive-Paris2016-Workflow/bin/console:43

make:docker:database [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

ping @dunglas

### PR DESCRIPTION
**Pull request by jrushlow**
Currently, `make:docker:database` only supports creating & manipulating `docker-compose.yaml` files. In the docker world however, it is common to have `docker-compose.yml` files. This PR adds support to manipulate existing `docker-compose`(`.yml`||`.yaml`) files.

When running this command without an existing compose file, `.yaml` will be used.

fixes #777

### CODE REVIEW

File: src/Maker/MakeDockerDatabase.php [hunk 1]
```diff
@@ -80,13 +80,22 @@ public function interact(InputInterface $input, ConsoleStyle $io, Command $comma
     {
         $io->section('- Docker Compose Setup-');
 
+        $composeFileExtensions = ['.yml', '.yaml'];
+        $composeFileExists = false;
         $composeFileContents = '';
         $statusMessage = 'Existing docker-compose.yaml not found: a new one will be generated!';
 
-        if ($this->fileManager->fileExists($this->composeFilePath)) {
-            $composeFileContents = $this->fileManager->getFileContents($this->composeFilePath);
```
Comment (weaverryan) [inline src/Maker/MakeDockerDatabase.php:87]: It looks like we currently calculate the `$this->composeFilePath` property in the constructor. Instead of doing that logic (and instead of having the inline logic here), could we remove that property and replace it with a `private function getComposeFilePath(): ?string`? That would loop over the possible paths and return the file path if it was found. Then, most of this section could stay the same, except that we would call the method instead of referencing the property.

Comment (jrushlow) [reply src/Maker/MakeDockerDatabase.php:87]: We need access to that property in `generate()` to be able to dump the new / update content. The latest commit adds a `getComposeFileContents()` that determines the file && grabs its contents if it exists. I think this is as close as we can get before we start abusing input args. 

We can revert the logic split back to inline if this implementation isn't as appetizing.

**Comment by weaverryan** [comment]
Thanks Jesse!
