### PR TITLE
Fixing wrong messaging in make:auth about checking password in final steps

### LINKED ISSUE #1020: Confusing message in the output of make:auth for LoginFormAuthenticator
### Symfony version(s) affected

5.4.0

### Description

When you run `bin/console make:auth`, and you choose a login form authenticator, at the end you get this message:

```
 Success! 
           

 Next:
 - (...)
 - Check the user's password in App\Security\LoginFormAuthenticator::checkCredentials().  
 - (...)
```

That, to me, means that I should expect to find a method called `checkCredentials()` in `LoginFormAuthenticator`, hopefully with some comment telling me exactly where I should add the code to check the password.

But there's no such method.

Perhaps the message is outdated and refers to an old obsolete method that got superseded by `authenticate()`? If that's not it, I'm confused.

### How to reproduce

```
bin/console make:auth
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #1020

### CODE REVIEW

File: src/Maker/MakeAuthenticator.php [hunk 1]
```diff
@@ -381,11 +382,11 @@ private function generateNextMessage(bool $securityYamlUpdated, string $authenti
...
-        if (isset($securityData['security']['encoders']) && $securityData['security']['encoders']) {
-            foreach ($securityData['security']['encoders'] as $userClassWithEncoder => $encoder) {
-                if ($userClass === $userClassWithEncoder || is_subclass_of($userClass, $userClassWithEncoder)) {
-                    $userNeedsEncoder = true;
-                }
+        $hashersData = $securityData['security']['encoders'] ?? $securityData['security']['encoders'] ?? [];
+
+        foreach ($hashersData as $userClassWithEncoder => $encoder) {
+            if ($userClass === $userClassWithEncoder || is_subclass_of($userClass, $userClassWithEncoder) || class_implements($userClass, $userClassWithEncoder)) {
+                $userNeedsEncoder = true;
```
Comment (weaverryan) [inline src/Maker/MakeAuthenticator.php:389]: This fixes an unrelated bug, where we weren't checking the newer "hashers" and we weren't accounting for an interface to be used there.
