### PR TITLE
Checking on reserved keywords for class name validity.

### LINKED ISSUE #305: If you try to create a new entity with the name "Class" the console crashes
**Symfony version(s) affected**: x.y.z
Symfony Installer version 1.5.11

**Description**  
If you try to create a new entity with the name "Class" the console crashes

**How to reproduce**  
 ./bin/console ma:ent
Class name of the entity to create or update (e.g. GentleGnome):
 > Class
 created: src/Entity/Class.php
 created: src/Repository/ClassRepository.php

In Class.php line 10:
                                                                               
  syntax error, unexpected 'Class' (T_CLASS), expecting identifier (T_STRING)  

(and if you try again)
./bin/console ma:ent
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, ...

**Possible Solution**  
Don't allow the name Class for new entity 
**Additional context**

### PR DESCRIPTION
**Pull request by SerkanYildiz**
Validator should also check if the given class name is a reserved keyword or not.
However we have to come up with a better exception message, since this one does not reflect the error. Any suggestion?

Thanks for your help @weaverryan during #SymfonyConHackDay2018

Fixes #305

### CODE REVIEW

File: src/Str.php [hunk 1]
```diff
@@ -197,6 +197,29 @@ public static function isValidPhpVariableName($name)
...
+            'exit', 'extends', 'final', 'for', 'foreach', 'function',
+            'global', 'goto', 'if', 'implements', 'include',
+            'include_once', 'instanceof', 'insteadof', 'interface', 'isset',
+            'list', 'namespace', 'new', 'or', 'print', 'private',
+            'protected', 'public', 'require', 'require_once', 'return',
+            'static', 'switch', 'throw', 'trait', 'try', 'unset',
+            'use', 'var', 'while', 'xor', '__CLASS__', '__DIR__', '__FILE__',
+            '__FUNCTION__', '__LINE__', '__METHOD__', '__NAMESPACE__', '__TRAIT__',
+            'int', 'float', 'bool', 'string', 'true', 'false', 'null', 'void',
+            'iterable', 'object',
```
Comment (sadikoff) [inline src/Str.php]: > 'int', 'float', 'bool', 'string', 'true', 'false', 'null', 'void',
            'iterable', 'object',

This words are allowed to use in Namespace, anyway it will be very strange to use it :-)

File: src/Validator.php [hunk 2]
```diff
@@ -29,7 +29,7 @@ public static function validateClassName(string $className, string $errorMessage
         $pieces = explode('\\', ltrim($className, '\\'));
 
         foreach ($pieces as $piece) {
-            if (!preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$/', $piece)) {
+            if (!Str::isValidPhpClassName($piece)) {
```
Comment (sadikoff) [inline src/Validator.php]: Maybe will be better not to change this check, but add a new check with new error message, to show the user what is wrong with classname?

**Comment by sadikoff** [comment]
@SerkanYildiz It's great that you have done it so fast, but I was talking about something else. I suggested not to split namespace and class validator, but leave old validation in place and add new one which will validate reserved words
ex:
```php
foreach ($pieces as $piece) {
    if (!preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$/', $piece)) {
        $errorMessage = $errorMessage ?: sprintf('"%s" is not valid as a PHP class name (it must start with a letter or underscore, followed by any number of letters, numbers, or underscores)', $className);
        throw new RuntimeCommandException($errorMessage);
    }
    if (Str::isPhpReservedWord($piece)) {
        throw new RuntimeCommandException(sprintf('"%s" is a reserved keyword and thus cannot be used as class name in PHP.', $className));
    }
}
```

**Comment by weaverryan** [comment]
Ping @SerkanYildiz! I think we need just one more small change. Does my description above make sense?

Cheers!

**Comment by SerkanYildiz** [comment]
@weaverryan Pushed the requested changes. Does it look good now?

**Comment by weaverryan** [comment]
Thank you @SerkanYildiz!
