### PR TITLE
[make:entity] confirm to allow non-ascii char's in entity names

### LINKED ISSUE #1556: [make:entity] Entity Names Should Be Allowed to Have Digits (i.e. v1)
Steps to reproduce:
- Use make:entity with a namespaced classname that includes a digit (i.e., Foo\v1\Bar)
- Observe ASCII error

https://github.com/symfony/maker-bundle/blob/6960c1cc31e8e4f8f1de6b8a139b7867092e5c13/src/Maker/MakeEntity.php#L832

Replace regex in line 832
`
Old = ^[a-zA-Z\\\\]+$
`
`
New = ^[a-zA-Z\\\d]+$
`

Removes duplicated \\ (escaped "\") and adds digit as allowable character.

### PR DESCRIPTION
**Pull request by Fan2Shrek**
Following the message https://github.com/symfony/maker-bundle/pull/1474#issuecomment-2027716072, I made some modifications

---
edited by @jrushlow 
fixes #1556

### CODE REVIEW

File: src/Maker/MakeEntity.php [hunk 1]
```diff
@@ -820,9 +819,11 @@ private function askRelationType(ConsoleStyle $io, string $entityClass, string $
         return $io->askQuestion($question);
     }
 
-    private function verifyEntityName(string $entityName): bool
+    private function verifyEntityName(string $entityName): array
     {
-        return preg_match('/^[a-zA-Z\\\\]+$/', $entityName);
+        preg_match('/[^\x00-\x7F]/u', $entityName, $matches);
```
Comment (jrushlow) [inline src/Maker/MakeEntity.php:824]:
```suggestion
        preg_match('/([^\x00-\x7F]+)/u', $entityName, $matches);
```

Comment (jrushlow) [reply src/Maker/MakeEntity.php:824]: We just need to know if the entity name contains any non-ascii's chars. Otherwise, we'd ask the questions multiple times which isnt very DX friendly...

File: src/Maker/MakeEntity.php [hunk 2]
```diff
@@ -131,10 +127,13 @@ public function interact(InputInterface $input, ConsoleStyle $io, Command $comma
 
         $argument = $command->getDefinition()->getArgument('name');
         $question = $this->createEntityClassQuestion($argument->getDescription());
-        $entityClassName = $io->askQuestion($question);
+        $entityClassName ??= $io->askQuestion($question);
+
+        while ($dangerous = $this->verifyEntityName($entityClassName)) {
+            if ($io->confirm(sprintf('The %s character is non-ASCII, which are potentially problematic with some database. It is recommended to use only ASCII characters in entity names. Would you keep entered name ?', $dangerous[0]), false)) {
```
Comment (jrushlow) [inline src/Maker/MakeEntity.php:133]:
```suggestion
            if ($io->confirm(sprintf('"%s" contains one or more non-ASCII characters, which are potentially problematic with some database. It is recommended to use only ASCII characters for entity names. Continue anyway?', $entityClassName), false)) {
```

**Review by jrushlow — APPROVED** [review]
Thank you @Fan2Shrek - I've suggested a couple minor changes which I'll go ahead and commit so we can merge.

File: src/Maker/MakeEntity.php [hunk 3]
```diff
@@ -820,9 +819,11 @@ private function askRelationType(ConsoleStyle $io, string $entityClass, string $
         return $io->askQuestion($question);
     }
 
-    private function verifyEntityName(string $entityName): bool
+    private function verifyEntityName(string $entityName): array
```
Comment (jrushlow) [inline src/Maker/MakeEntity.php:822]:
```suggestion
    /** @return string[] */
    private function verifyEntityName(string $entityName): array
```
